# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
       - image: circleci/node:8
    working_directory: ~/repo
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
          - c5:72:a3:d9:d7:c8:27:c7:4c:62:1c:24:64:b7:84:1c
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache: # special step to restore the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: # run tests
          name: test
          command: npm test
      - run:
          name: deploy
          command: |
            if [ "$CIRCLE_BRANCH" == "master" ]; then
              echo 'Deploying to production';
              ssh -o "StrictHostKeyChecking no" root@138.197.70.99 "cd /root/visualcosita; git reset --hard origin/master; ./build_and_deploy_to_swarm.sh"
            else
              echo 'Not master branch, skipping deploy to production'
            fi

      # collect reports
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
